namespace: kube-system

nvidia:
  image: ghcr.io/suse/nvidia-driver-installer:0.1.0
  nodeSelector:
    node-role.kubernetes.io/ai-worker: "true"

os:
  sles:
    regcode: ""
    regemail: ""
    driverVersion: "575.57.08"
  slem:
    regcode: ""
    regemail: ""
    driverVersion: "570.133.20"

kured:
  image: ghcr.io/kubereboot/kured:1.17.1
  updatePeriod: "1m"
  rebootSentinel: "/sentinel/reboot-needed"
