apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-driver-installer-config
  namespace: {{ .Values.namespace }}
data:
  SLES_DRIVER_VERSION: "{{ .Values.os.sles.driverVersion }}"
  SLEM_DRIVER_VERSION: "{{ .Values.os.slem.driverVersion }}"
