apiVersion: v1
kind: Secret
metadata:
  name: sles-regcode
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  regcode: {{ .Values.os.sles.regcode | b64enc | quote }}
  regemail: {{ .Values.os.sles.regemail | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: slem-regcode
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  regcode: {{ .Values.os.slem.regcode | b64enc | quote }}
  regemail: {{ .Values.os.slem.regemail | b64enc | quote }}
