name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - id: tags
      name: Calculate tags
      shell: bash
      run: |
        BASE=ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        ref=${{ github.ref }}
        # Docker image tag
        case "$ref" in
          refs/heads/main)
            IMAGE_TAG="$BASE:latest";;
          refs/tags/*)
            IMAGE_TAG="$BASE:${ref#refs/tags/}";;
          *)
            IMAGE_TAG="$BASE:${{ github.sha }}";;
        esac
        
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "BASE=$BASE" >> $GITHUB_ENV
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v3
      with:
        platforms: |
          linux/amd64
          linux/arm64
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        platforms: |
          linux/amd64
          linux/arm64
        push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        tags: ${{ env.IMAGE_TAG }}
    - name: Build Helm chart and publish to GitHub Packages
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      run: |
        helm package ./chart
        echo "Chart Tag generated: ${{ env.BASE }}"
        helm push ./nvidia-driver-installer*.tgz oci://ghcr.io/suse/chart
